server:
  port: 8070
  servlet:
    context-path: /consumer

spring:
  application:
    name: music-consumer
  rabbitmq:
    addresses: 192.168.6.128
    username: guest
    password: guest
    port: 5672